[package]
name = "git_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.0.2"
miniz_oxide = "0.7.1"
sha1 = "0.10.6"
